name: Docker Build & Publish

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Login en GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Build de la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/books-review/book-app:latest .
          docker tag ghcr.io/${{ github.repository_owner }}/books-review/book-app:latest ghcr.io/${{ github.repository_owner }}/books-review/book-app:${{ github.sha }}

      # 4. Push de la imagen a GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/books-review/book-app:latest
          docker push ghcr.io/${{ github.repository_owner }}/books-review/book-app:${{ github.sha }}
