name: Docker Build & Publish

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/book-app:latest .
          docker tag ghcr.io/${{ github.repository }}/book-app:latest ghcr.io/${{ github.repository }}/book-app:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/book-app:latest
          docker push ghcr.io/${{ github.repository }}/book-app:${{ github.sha }}
